server:
  port: 8081
spring:
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.198.187.152:3306/INVENTORY?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: LINGsheng1026*
  application:
    name: inventory
  cloud:
    nacos:
      discovery:
        server-addr: 139.198.187.152:8848
        group: DEFAULT_GROUP
feign:
  httpclient:
    enabled: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



