server:
  port: 8081
spring:
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  application:
    name: inventory-provider
  cloud:
    nacos:
      discovery:
        server-addr: 49.235.123.253:8848
        group: DEFAULT_GROUP
dubbo:
  application:
    name: inventory-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



